DECLARE
PROCEDURE INSERTLAB(id NUMBER, val NUMBER) IS
BEGIN
INSERT INTO MyTable(id, val) VALUES(id, val);
END INSERTLAB;
PROCEDURE UPDATELAB(up_id NUMBER, val_new NUMBER) IS
BEGIN
UPDATE MyTable SET val = val_new WHERE id = up_id;
END UPDATELAB;
PROCEDURE DELETELAB(id NUMBER) IS
BEGIN
DELETE FROM MyTable WHERE id = id;
END DELETELAB;

BEGIN
INSERTLAB(10005, 130);
UPDATELAB(10005, 170);
DELETELAB(10005);
END;